version: '3'
networks:
  aurora-net:
    driver: bridge
volumes:
    aurora_prometheus_data: {}
    aurora_grafana_data: {}
services:
  aurora:
    image: aurora:latest
    container_name: aurora-main
    ports:
      - "2112"
    networks:
      - aurora-net
    volumes:
      - ../test/data:/test/data

  prometheus:
    image: prom/prometheus:latest
    container_name: aurora-prom
    volumes:
      - aurora_prometheus_data:/prometheus
      - ../configs/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=31d'
      - '--web.enable-lifecycle'
    ports:
      - "9090"
    networks:
      - aurora-net

  grafana:
    image: grafana/grafana:latest
    container_name: aurora-grafana
    volumes:
      - aurora_grafana_data:/var/lib/grafana
      - ../configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000"
    networks:
      - aurora-net
