{
 "title": "Aurora",
 "description": "Information about the application.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ad Hoc Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Files in watched folder recently written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "metrics_folder_watcher_events{operations=\"WRITE\"}",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  { "title": "Go Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Go Application Build Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aurora_version_info" }
   ]
  },
  {
   "title": "Process CPU Seconds over 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} - bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "{{job}} - alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{job}} - stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{job}} - heap inuse" }
   ]
  },
  {
   "title": "Go Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} - resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}} - virtual" }
   ]
  },
  {
   "title": "Go Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}